// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto
// Protobuf C++ Version: 6.33.4

#include "messages.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace CheatHaram {

inline constexpr PlayerData::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        server_ip_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_{0},
        in_game_{false} {}

template <typename>
PROTOBUF_CONSTEXPR PlayerData::PlayerData(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PlayerData_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PlayerDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PlayerDataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PlayerDataDefaultTypeInternal() {}
  union {
    PlayerData _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PlayerDataDefaultTypeInternal _PlayerData_default_instance_;

inline constexpr Player::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        guid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Player::Player(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Player_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PlayerDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PlayerDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PlayerDefaultTypeInternal() {}
  union {
    Player _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PlayerDefaultTypeInternal _Player_default_instance_;

inline constexpr S2C_Message::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        hashes_{},
        players_list_{},
        message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        guid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        dll_bytes_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        dll_hash_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        dll_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        action_{static_cast< ::CheatHaram::ActionType >(0)},
        success_{false} {}

template <typename>
PROTOBUF_CONSTEXPR S2C_Message::S2C_Message(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(S2C_Message_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct S2C_MessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR S2C_MessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~S2C_MessageDefaultTypeInternal() {}
  union {
    S2C_Message _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 S2C_MessageDefaultTypeInternal _S2C_Message_default_instance_;

inline constexpr C2S_Message::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        signature_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        hwid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        image_data_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        target_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        player_data_{nullptr},
        timestamp_{::uint64_t{0u}},
        action_{static_cast< ::CheatHaram::ActionType >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR C2S_Message::C2S_Message(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(C2S_Message_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct C2S_MessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR C2S_MessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~C2S_MessageDefaultTypeInternal() {}
  union {
    C2S_Message _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 C2S_MessageDefaultTypeInternal _C2S_Message_default_instance_;
}  // namespace CheatHaram
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_messages_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_messages_2eproto = nullptr;
const ::uint32_t
    TableStruct_messages_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::CheatHaram::Player, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::CheatHaram::Player, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::CheatHaram::Player, _impl_.guid_),
        PROTOBUF_FIELD_OFFSET(::CheatHaram::Player, _impl_.name_),
        2,
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::CheatHaram::PlayerData, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::CheatHaram::PlayerData, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::CheatHaram::PlayerData, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::CheatHaram::PlayerData, _impl_.server_ip_),
        PROTOBUF_FIELD_OFFSET(::CheatHaram::PlayerData, _impl_.in_game_),
        2,
        0,
        1,
        3,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::CheatHaram::C2S_Message, _impl_._has_bits_),
        10, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::CheatHaram::C2S_Message, _impl_.action_),
        PROTOBUF_FIELD_OFFSET(::CheatHaram::C2S_Message, _impl_.timestamp_),
        PROTOBUF_FIELD_OFFSET(::CheatHaram::C2S_Message, _impl_.signature_),
        PROTOBUF_FIELD_OFFSET(::CheatHaram::C2S_Message, _impl_.hwid_),
        PROTOBUF_FIELD_OFFSET(::CheatHaram::C2S_Message, _impl_.player_data_),
        PROTOBUF_FIELD_OFFSET(::CheatHaram::C2S_Message, _impl_.image_data_),
        PROTOBUF_FIELD_OFFSET(::CheatHaram::C2S_Message, _impl_.target_),
        6,
        5,
        0,
        1,
        4,
        2,
        3,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::CheatHaram::S2C_Message, _impl_._has_bits_),
        12, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::CheatHaram::S2C_Message, _impl_.action_),
        PROTOBUF_FIELD_OFFSET(::CheatHaram::S2C_Message, _impl_.success_),
        PROTOBUF_FIELD_OFFSET(::CheatHaram::S2C_Message, _impl_.message_),
        PROTOBUF_FIELD_OFFSET(::CheatHaram::S2C_Message, _impl_.guid_),
        PROTOBUF_FIELD_OFFSET(::CheatHaram::S2C_Message, _impl_.hashes_),
        PROTOBUF_FIELD_OFFSET(::CheatHaram::S2C_Message, _impl_.dll_bytes_),
        PROTOBUF_FIELD_OFFSET(::CheatHaram::S2C_Message, _impl_.dll_hash_),
        PROTOBUF_FIELD_OFFSET(::CheatHaram::S2C_Message, _impl_.dll_name_),
        PROTOBUF_FIELD_OFFSET(::CheatHaram::S2C_Message, _impl_.players_list_),
        7,
        8,
        2,
        3,
        0,
        4,
        5,
        6,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::CheatHaram::Player)},
        {9, sizeof(::CheatHaram::PlayerData)},
        {20, sizeof(::CheatHaram::C2S_Message)},
        {37, sizeof(::CheatHaram::S2C_Message)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::CheatHaram::_Player_default_instance_._instance,
    &::CheatHaram::_PlayerData_default_instance_._instance,
    &::CheatHaram::_C2S_Message_default_instance_._instance,
    &::CheatHaram::_S2C_Message_default_instance_._instance,
};
const char descriptor_table_protodef_messages_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016messages.proto\022\nCheatHaram\"0\n\006Player\022\n"
    "\n\002id\030\001 \001(\005\022\014\n\004guid\030\002 \001(\t\022\014\n\004name\030\003 \001(\t\"J"
    "\n\nPlayerData\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\021"
    "\n\tserver_ip\030\003 \001(\t\022\017\n\007in_game\030\004 \001(\010\"\272\001\n\013C"
    "2S_Message\022&\n\006action\030\001 \001(\0162\026.CheatHaram."
    "ActionType\022\021\n\ttimestamp\030\002 \001(\004\022\021\n\tsignatu"
    "re\030\003 \001(\t\022\014\n\004hwid\030\004 \001(\t\022+\n\013player_data\030\005 "
    "\001(\0132\026.CheatHaram.PlayerData\022\022\n\nimage_dat"
    "a\030\006 \001(\014\022\016\n\006target\030\007 \001(\t\"\326\001\n\013S2C_Message\022"
    "&\n\006action\030\001 \001(\0162\026.CheatHaram.ActionType\022"
    "\017\n\007success\030\002 \001(\010\022\017\n\007message\030\003 \001(\t\022\014\n\004gui"
    "d\030\004 \001(\t\022\016\n\006hashes\030\005 \003(\t\022\021\n\tdll_bytes\030\006 \001"
    "(\014\022\020\n\010dll_hash\030\007 \001(\t\022\020\n\010dll_name\030\010 \001(\t\022("
    "\n\014players_list\030\t \003(\0132\022.CheatHaram.Player"
    "*\324\002\n\nActionType\022\013\n\007UNKNOWN\020\000\022\020\n\014AUTH_REQ"
    "UEST\020\001\022\017\n\013AUTH_RESULT\020\002\022\025\n\021PK3_WHITELIST"
    "_REQ\020\003\022\030\n\024PK3_WHITELIST_RESULT\020\004\022\017\n\013PAYL"
    "OAD_REQ\020\005\022\022\n\016PAYLOAD_RESULT\020\006\022\014\n\010SET_GUI"
    "D\020\007\022\020\n\014CRASH_CLIENT\020\010\022\023\n\017PLAYER_LIST_REQ"
    "\020\t\022\026\n\022PLAYER_LIST_RESULT\020\n\022\021\n\rTAKE_FAIRS"
    "HOT\020\013\022\024\n\020REQUEST_FAIRSHOT\020\014\022\r\n\tHEARTBEAT"
    "\020\r\022\027\n\023UPDATE_PLAYER_STATE\020\016\022\020\n\014GET_GUID_"
    "REQ\020\017\022\020\n\014FAIRSHOT_ACK\020\020b\006proto3"
};
static ::absl::once_flag descriptor_table_messages_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_messages_2eproto = {
    false,
    false,
    911,
    descriptor_table_protodef_messages_2eproto,
    "messages.proto",
    &descriptor_table_messages_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_messages_2eproto::offsets,
    file_level_enum_descriptors_messages_2eproto,
    file_level_service_descriptors_messages_2eproto,
};
namespace CheatHaram {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL ActionType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_messages_2eproto);
  return file_level_enum_descriptors_messages_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t ActionType_internal_data_[] = {
    1114112u, 0u, };
// ===================================================================

class Player::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Player>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Player, _impl_._has_bits_);
};

Player::Player(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Player_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CheatHaram.Player)
}
PROTOBUF_NDEBUG_INLINE Player::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::CheatHaram::Player& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        guid_(arena, from.guid_),
        name_(arena, from.name_) {}

Player::Player(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Player& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Player_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Player* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.id_ = from._impl_.id_;

  // @@protoc_insertion_point(copy_constructor:CheatHaram.Player)
}
PROTOBUF_NDEBUG_INLINE Player::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        guid_(arena),
        name_(arena) {}

inline void Player::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.id_ = {};
}
Player::~Player() {
  // @@protoc_insertion_point(destructor:CheatHaram.Player)
  SharedDtor(*this);
}
inline void Player::SharedDtor(MessageLite& self) {
  Player& this_ = static_cast<Player&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.guid_.Destroy();
  this_._impl_.name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Player::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Player(arena);
}
constexpr auto Player::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Player),
                                            alignof(Player));
}
constexpr auto Player::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Player_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Player::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Player>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Player::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Player>(), &Player::ByteSizeLong,
              &Player::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Player, _impl_._cached_size_),
          false,
      },
      &Player::kDescriptorMethods,
      &descriptor_table_messages_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Player_class_data_ =
        Player::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Player::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Player_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Player_class_data_.tc_table);
  return Player_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 34, 2>
Player::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Player, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Player_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::CheatHaram::Player>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Player, _impl_.id_), 2>(),
     {8, 2, 0,
      PROTOBUF_FIELD_OFFSET(Player, _impl_.id_)}},
    // string guid = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(Player, _impl_.guid_)}},
    // string name = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 1, 0,
      PROTOBUF_FIELD_OFFSET(Player, _impl_.name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 id = 1;
    {PROTOBUF_FIELD_OFFSET(Player, _impl_.id_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // string guid = 2;
    {PROTOBUF_FIELD_OFFSET(Player, _impl_.guid_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string name = 3;
    {PROTOBUF_FIELD_OFFSET(Player, _impl_.name_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\21\0\4\4\0\0\0\0"
    "CheatHaram.Player"
    "guid"
    "name"
  }},
};
PROTOBUF_NOINLINE void Player::Clear() {
// @@protoc_insertion_point(message_clear_start:CheatHaram.Player)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.guid_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.name_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.id_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Player::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Player& this_ = static_cast<const Player&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Player::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Player& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:CheatHaram.Player)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_id(), target);
    }
  }

  // string guid = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_guid().empty()) {
      const ::std::string& _s = this_._internal_guid();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "CheatHaram.Player.guid");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // string name = 3;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_name().empty()) {
      const ::std::string& _s = this_._internal_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "CheatHaram.Player.name");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CheatHaram.Player)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Player::ByteSizeLong(const MessageLite& base) {
  const Player& this_ = static_cast<const Player&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Player::ByteSizeLong() const {
  const Player& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:CheatHaram.Player)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // string guid = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_guid().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_guid());
      }
    }
    // string name = 3;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_name());
      }
    }
    // int32 id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_id());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Player::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Player*>(&to_msg);
  auto& from = static_cast<const Player&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:CheatHaram.Player)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_guid().empty()) {
        _this->_internal_set_guid(from._internal_guid());
      } else {
        if (_this->_impl_.guid_.IsDefault()) {
          _this->_internal_set_guid("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_name().empty()) {
        _this->_internal_set_name(from._internal_name());
      } else {
        if (_this->_impl_.name_.IsDefault()) {
          _this->_internal_set_name("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_id() != 0) {
        _this->_impl_.id_ = from._impl_.id_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Player::CopyFrom(const Player& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:CheatHaram.Player)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Player::InternalSwap(Player* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.guid_, &other->_impl_.guid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  swap(_impl_.id_, other->_impl_.id_);
}

::google::protobuf::Metadata Player::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PlayerData::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PlayerData>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PlayerData, _impl_._has_bits_);
};

PlayerData::PlayerData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PlayerData_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CheatHaram.PlayerData)
}
PROTOBUF_NDEBUG_INLINE PlayerData::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::CheatHaram::PlayerData& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        name_(arena, from.name_),
        server_ip_(arena, from.server_ip_) {}

PlayerData::PlayerData(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PlayerData& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PlayerData_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PlayerData* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, id_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, id_),
           offsetof(Impl_, in_game_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::in_game_));

  // @@protoc_insertion_point(copy_constructor:CheatHaram.PlayerData)
}
PROTOBUF_NDEBUG_INLINE PlayerData::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        name_(arena),
        server_ip_(arena) {}

inline void PlayerData::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, in_game_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::in_game_));
}
PlayerData::~PlayerData() {
  // @@protoc_insertion_point(destructor:CheatHaram.PlayerData)
  SharedDtor(*this);
}
inline void PlayerData::SharedDtor(MessageLite& self) {
  PlayerData& this_ = static_cast<PlayerData&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  this_._impl_.server_ip_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PlayerData::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PlayerData(arena);
}
constexpr auto PlayerData::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PlayerData),
                                            alignof(PlayerData));
}
constexpr auto PlayerData::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PlayerData_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PlayerData::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PlayerData>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PlayerData::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PlayerData>(), &PlayerData::ByteSizeLong,
              &PlayerData::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PlayerData, _impl_._cached_size_),
          false,
      },
      &PlayerData::kDescriptorMethods,
      &descriptor_table_messages_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PlayerData_class_data_ =
        PlayerData::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PlayerData::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PlayerData_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PlayerData_class_data_.tc_table);
  return PlayerData_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 43, 2>
PlayerData::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PlayerData, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    PlayerData_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::CheatHaram::PlayerData>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool in_game = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(PlayerData, _impl_.in_game_), 3>(),
     {32, 3, 0,
      PROTOBUF_FIELD_OFFSET(PlayerData, _impl_.in_game_)}},
    // int32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PlayerData, _impl_.id_), 2>(),
     {8, 2, 0,
      PROTOBUF_FIELD_OFFSET(PlayerData, _impl_.id_)}},
    // string name = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(PlayerData, _impl_.name_)}},
    // string server_ip = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 1, 0,
      PROTOBUF_FIELD_OFFSET(PlayerData, _impl_.server_ip_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 id = 1;
    {PROTOBUF_FIELD_OFFSET(PlayerData, _impl_.id_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // string name = 2;
    {PROTOBUF_FIELD_OFFSET(PlayerData, _impl_.name_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string server_ip = 3;
    {PROTOBUF_FIELD_OFFSET(PlayerData, _impl_.server_ip_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bool in_game = 4;
    {PROTOBUF_FIELD_OFFSET(PlayerData, _impl_.in_game_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
    "\25\0\4\11\0\0\0\0"
    "CheatHaram.PlayerData"
    "name"
    "server_ip"
  }},
};
PROTOBUF_NOINLINE void PlayerData::Clear() {
// @@protoc_insertion_point(message_clear_start:CheatHaram.PlayerData)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.name_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.server_ip_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000000cU)) {
    ::memset(&_impl_.id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.in_game_) -
        reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.in_game_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PlayerData::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PlayerData& this_ = static_cast<const PlayerData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PlayerData::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PlayerData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:CheatHaram.PlayerData)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_id(), target);
    }
  }

  // string name = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_name().empty()) {
      const ::std::string& _s = this_._internal_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "CheatHaram.PlayerData.name");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // string server_ip = 3;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_server_ip().empty()) {
      const ::std::string& _s = this_._internal_server_ip();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "CheatHaram.PlayerData.server_ip");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  // bool in_game = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_in_game() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          4, this_._internal_in_game(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CheatHaram.PlayerData)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PlayerData::ByteSizeLong(const MessageLite& base) {
  const PlayerData& this_ = static_cast<const PlayerData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PlayerData::ByteSizeLong() const {
  const PlayerData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:CheatHaram.PlayerData)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // string name = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_name());
      }
    }
    // string server_ip = 3;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_server_ip().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_server_ip());
      }
    }
    // int32 id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_id());
      }
    }
    // bool in_game = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_in_game() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PlayerData::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<PlayerData*>(&to_msg);
  auto& from = static_cast<const PlayerData&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:CheatHaram.PlayerData)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_name().empty()) {
        _this->_internal_set_name(from._internal_name());
      } else {
        if (_this->_impl_.name_.IsDefault()) {
          _this->_internal_set_name("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_server_ip().empty()) {
        _this->_internal_set_server_ip(from._internal_server_ip());
      } else {
        if (_this->_impl_.server_ip_.IsDefault()) {
          _this->_internal_set_server_ip("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_id() != 0) {
        _this->_impl_.id_ = from._impl_.id_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_in_game() != 0) {
        _this->_impl_.in_game_ = from._impl_.in_game_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void PlayerData::CopyFrom(const PlayerData& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:CheatHaram.PlayerData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PlayerData::InternalSwap(PlayerData* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.server_ip_, &other->_impl_.server_ip_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PlayerData, _impl_.in_game_)
      + sizeof(PlayerData::_impl_.in_game_)
      - PROTOBUF_FIELD_OFFSET(PlayerData, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata PlayerData::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class C2S_Message::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<C2S_Message>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(C2S_Message, _impl_._has_bits_);
};

C2S_Message::C2S_Message(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, C2S_Message_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CheatHaram.C2S_Message)
}
PROTOBUF_NDEBUG_INLINE C2S_Message::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::CheatHaram::C2S_Message& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        signature_(arena, from.signature_),
        hwid_(arena, from.hwid_),
        image_data_(arena, from.image_data_),
        target_(arena, from.target_) {}

C2S_Message::C2S_Message(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const C2S_Message& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, C2S_Message_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  C2S_Message* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.player_data_ = (CheckHasBit(cached_has_bits, 0x00000010U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.player_data_)
                : nullptr;
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, timestamp_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, timestamp_),
           offsetof(Impl_, action_) -
               offsetof(Impl_, timestamp_) +
               sizeof(Impl_::action_));

  // @@protoc_insertion_point(copy_constructor:CheatHaram.C2S_Message)
}
PROTOBUF_NDEBUG_INLINE C2S_Message::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        signature_(arena),
        hwid_(arena),
        image_data_(arena),
        target_(arena) {}

inline void C2S_Message::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, player_data_),
           0,
           offsetof(Impl_, action_) -
               offsetof(Impl_, player_data_) +
               sizeof(Impl_::action_));
}
C2S_Message::~C2S_Message() {
  // @@protoc_insertion_point(destructor:CheatHaram.C2S_Message)
  SharedDtor(*this);
}
inline void C2S_Message::SharedDtor(MessageLite& self) {
  C2S_Message& this_ = static_cast<C2S_Message&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.signature_.Destroy();
  this_._impl_.hwid_.Destroy();
  this_._impl_.image_data_.Destroy();
  this_._impl_.target_.Destroy();
  delete this_._impl_.player_data_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL C2S_Message::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) C2S_Message(arena);
}
constexpr auto C2S_Message::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(C2S_Message),
                                            alignof(C2S_Message));
}
constexpr auto C2S_Message::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_C2S_Message_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &C2S_Message::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<C2S_Message>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &C2S_Message::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<C2S_Message>(), &C2S_Message::ByteSizeLong,
              &C2S_Message::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(C2S_Message, _impl_._cached_size_),
          false,
      },
      &C2S_Message::kDescriptorMethods,
      &descriptor_table_messages_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull C2S_Message_class_data_ =
        C2S_Message::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
C2S_Message::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&C2S_Message_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(C2S_Message_class_data_.tc_table);
  return C2S_Message_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 7, 1, 50, 2>
C2S_Message::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(C2S_Message, _impl_._has_bits_),
    0, // no _extensions_
    7, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967168,  // skipmap
    offsetof(decltype(_table_), field_entries),
    7,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    C2S_Message_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::CheatHaram::C2S_Message>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .CheatHaram.ActionType action = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(C2S_Message, _impl_.action_), 6>(),
     {8, 6, 0,
      PROTOBUF_FIELD_OFFSET(C2S_Message, _impl_.action_)}},
    // uint64 timestamp = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(C2S_Message, _impl_.timestamp_), 5>(),
     {16, 5, 0,
      PROTOBUF_FIELD_OFFSET(C2S_Message, _impl_.timestamp_)}},
    // string signature = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 0, 0,
      PROTOBUF_FIELD_OFFSET(C2S_Message, _impl_.signature_)}},
    // string hwid = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 1, 0,
      PROTOBUF_FIELD_OFFSET(C2S_Message, _impl_.hwid_)}},
    // .CheatHaram.PlayerData player_data = 5;
    {::_pbi::TcParser::FastMtS1,
     {42, 4, 0,
      PROTOBUF_FIELD_OFFSET(C2S_Message, _impl_.player_data_)}},
    // bytes image_data = 6;
    {::_pbi::TcParser::FastBS1,
     {50, 2, 0,
      PROTOBUF_FIELD_OFFSET(C2S_Message, _impl_.image_data_)}},
    // string target = 7;
    {::_pbi::TcParser::FastUS1,
     {58, 3, 0,
      PROTOBUF_FIELD_OFFSET(C2S_Message, _impl_.target_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .CheatHaram.ActionType action = 1;
    {PROTOBUF_FIELD_OFFSET(C2S_Message, _impl_.action_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // uint64 timestamp = 2;
    {PROTOBUF_FIELD_OFFSET(C2S_Message, _impl_.timestamp_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // string signature = 3;
    {PROTOBUF_FIELD_OFFSET(C2S_Message, _impl_.signature_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string hwid = 4;
    {PROTOBUF_FIELD_OFFSET(C2S_Message, _impl_.hwid_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .CheatHaram.PlayerData player_data = 5;
    {PROTOBUF_FIELD_OFFSET(C2S_Message, _impl_.player_data_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // bytes image_data = 6;
    {PROTOBUF_FIELD_OFFSET(C2S_Message, _impl_.image_data_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // string target = 7;
    {PROTOBUF_FIELD_OFFSET(C2S_Message, _impl_.target_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::CheatHaram::PlayerData>()},
  }},
  {{
    "\26\0\0\11\4\0\0\6"
    "CheatHaram.C2S_Message"
    "signature"
    "hwid"
    "target"
  }},
};
PROTOBUF_NOINLINE void C2S_Message::Clear() {
// @@protoc_insertion_point(message_clear_start:CheatHaram.C2S_Message)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.signature_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.hwid_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.image_data_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _impl_.target_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      ABSL_DCHECK(_impl_.player_data_ != nullptr);
      _impl_.player_data_->Clear();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000060U)) {
    ::memset(&_impl_.timestamp_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.action_) -
        reinterpret_cast<char*>(&_impl_.timestamp_)) + sizeof(_impl_.action_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL C2S_Message::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const C2S_Message& this_ = static_cast<const C2S_Message&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL C2S_Message::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const C2S_Message& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:CheatHaram.C2S_Message)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .CheatHaram.ActionType action = 1;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    if (this_._internal_action() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          1, this_._internal_action(), target);
    }
  }

  // uint64 timestamp = 2;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (this_._internal_timestamp() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          2, this_._internal_timestamp(), target);
    }
  }

  // string signature = 3;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_signature().empty()) {
      const ::std::string& _s = this_._internal_signature();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "CheatHaram.C2S_Message.signature");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  // string hwid = 4;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_hwid().empty()) {
      const ::std::string& _s = this_._internal_hwid();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "CheatHaram.C2S_Message.hwid");
      target = stream->WriteStringMaybeAliased(4, _s, target);
    }
  }

  // .CheatHaram.PlayerData player_data = 5;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        5, *this_._impl_.player_data_, this_._impl_.player_data_->GetCachedSize(), target,
        stream);
  }

  // bytes image_data = 6;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_image_data().empty()) {
      const ::std::string& _s = this_._internal_image_data();
      target = stream->WriteBytesMaybeAliased(6, _s, target);
    }
  }

  // string target = 7;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (!this_._internal_target().empty()) {
      const ::std::string& _s = this_._internal_target();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "CheatHaram.C2S_Message.target");
      target = stream->WriteStringMaybeAliased(7, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CheatHaram.C2S_Message)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t C2S_Message::ByteSizeLong(const MessageLite& base) {
  const C2S_Message& this_ = static_cast<const C2S_Message&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t C2S_Message::ByteSizeLong() const {
  const C2S_Message& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:CheatHaram.C2S_Message)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000007fU)) {
    // string signature = 3;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_signature().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_signature());
      }
    }
    // string hwid = 4;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_hwid().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_hwid());
      }
    }
    // bytes image_data = 6;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_image_data().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_image_data());
      }
    }
    // string target = 7;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!this_._internal_target().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_target());
      }
    }
    // .CheatHaram.PlayerData player_data = 5;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.player_data_);
    }
    // uint64 timestamp = 2;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (this_._internal_timestamp() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_timestamp());
      }
    }
    // .CheatHaram.ActionType action = 1;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (this_._internal_action() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_action());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void C2S_Message::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<C2S_Message*>(&to_msg);
  auto& from = static_cast<const C2S_Message&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:CheatHaram.C2S_Message)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000007fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_signature().empty()) {
        _this->_internal_set_signature(from._internal_signature());
      } else {
        if (_this->_impl_.signature_.IsDefault()) {
          _this->_internal_set_signature("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_hwid().empty()) {
        _this->_internal_set_hwid(from._internal_hwid());
      } else {
        if (_this->_impl_.hwid_.IsDefault()) {
          _this->_internal_set_hwid("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_image_data().empty()) {
        _this->_internal_set_image_data(from._internal_image_data());
      } else {
        if (_this->_impl_.image_data_.IsDefault()) {
          _this->_internal_set_image_data("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!from._internal_target().empty()) {
        _this->_internal_set_target(from._internal_target());
      } else {
        if (_this->_impl_.target_.IsDefault()) {
          _this->_internal_set_target("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      ABSL_DCHECK(from._impl_.player_data_ != nullptr);
      if (_this->_impl_.player_data_ == nullptr) {
        _this->_impl_.player_data_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.player_data_);
      } else {
        _this->_impl_.player_data_->MergeFrom(*from._impl_.player_data_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (from._internal_timestamp() != 0) {
        _this->_impl_.timestamp_ = from._impl_.timestamp_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (from._internal_action() != 0) {
        _this->_impl_.action_ = from._impl_.action_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void C2S_Message::CopyFrom(const C2S_Message& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:CheatHaram.C2S_Message)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void C2S_Message::InternalSwap(C2S_Message* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.signature_, &other->_impl_.signature_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.hwid_, &other->_impl_.hwid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.image_data_, &other->_impl_.image_data_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.target_, &other->_impl_.target_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(C2S_Message, _impl_.action_)
      + sizeof(C2S_Message::_impl_.action_)
      - PROTOBUF_FIELD_OFFSET(C2S_Message, _impl_.player_data_)>(
          reinterpret_cast<char*>(&_impl_.player_data_),
          reinterpret_cast<char*>(&other->_impl_.player_data_));
}

::google::protobuf::Metadata C2S_Message::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class S2C_Message::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<S2C_Message>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(S2C_Message, _impl_._has_bits_);
};

S2C_Message::S2C_Message(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, S2C_Message_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CheatHaram.S2C_Message)
}
PROTOBUF_NDEBUG_INLINE S2C_Message::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::CheatHaram::S2C_Message& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        hashes_{visibility, arena, from.hashes_},
        players_list_{visibility, arena, from.players_list_},
        message_(arena, from.message_),
        guid_(arena, from.guid_),
        dll_bytes_(arena, from.dll_bytes_),
        dll_hash_(arena, from.dll_hash_),
        dll_name_(arena, from.dll_name_) {}

S2C_Message::S2C_Message(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const S2C_Message& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, S2C_Message_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  S2C_Message* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, action_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, action_),
           offsetof(Impl_, success_) -
               offsetof(Impl_, action_) +
               sizeof(Impl_::success_));

  // @@protoc_insertion_point(copy_constructor:CheatHaram.S2C_Message)
}
PROTOBUF_NDEBUG_INLINE S2C_Message::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        hashes_{visibility, arena},
        players_list_{visibility, arena},
        message_(arena),
        guid_(arena),
        dll_bytes_(arena),
        dll_hash_(arena),
        dll_name_(arena) {}

inline void S2C_Message::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, action_),
           0,
           offsetof(Impl_, success_) -
               offsetof(Impl_, action_) +
               sizeof(Impl_::success_));
}
S2C_Message::~S2C_Message() {
  // @@protoc_insertion_point(destructor:CheatHaram.S2C_Message)
  SharedDtor(*this);
}
inline void S2C_Message::SharedDtor(MessageLite& self) {
  S2C_Message& this_ = static_cast<S2C_Message&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.message_.Destroy();
  this_._impl_.guid_.Destroy();
  this_._impl_.dll_bytes_.Destroy();
  this_._impl_.dll_hash_.Destroy();
  this_._impl_.dll_name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL S2C_Message::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) S2C_Message(arena);
}
constexpr auto S2C_Message::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(S2C_Message, _impl_.hashes_) +
          decltype(S2C_Message::_impl_.hashes_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(S2C_Message, _impl_.players_list_) +
          decltype(S2C_Message::_impl_.players_list_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(S2C_Message), alignof(S2C_Message), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&S2C_Message::PlacementNew_,
                                 sizeof(S2C_Message),
                                 alignof(S2C_Message));
  }
}
constexpr auto S2C_Message::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_S2C_Message_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &S2C_Message::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<S2C_Message>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &S2C_Message::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<S2C_Message>(), &S2C_Message::ByteSizeLong,
              &S2C_Message::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(S2C_Message, _impl_._cached_size_),
          false,
      },
      &S2C_Message::kDescriptorMethods,
      &descriptor_table_messages_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull S2C_Message_class_data_ =
        S2C_Message::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
S2C_Message::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&S2C_Message_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(S2C_Message_class_data_.tc_table);
  return S2C_Message_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 9, 1, 72, 2>
S2C_Message::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(S2C_Message, _impl_._has_bits_),
    0, // no _extensions_
    9, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294966784,  // skipmap
    offsetof(decltype(_table_), field_entries),
    9,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    S2C_Message_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::CheatHaram::S2C_Message>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .CheatHaram.ActionType action = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(S2C_Message, _impl_.action_), 7>(),
     {8, 7, 0,
      PROTOBUF_FIELD_OFFSET(S2C_Message, _impl_.action_)}},
    // bool success = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(S2C_Message, _impl_.success_), 8>(),
     {16, 8, 0,
      PROTOBUF_FIELD_OFFSET(S2C_Message, _impl_.success_)}},
    // string message = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 2, 0,
      PROTOBUF_FIELD_OFFSET(S2C_Message, _impl_.message_)}},
    // string guid = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 3, 0,
      PROTOBUF_FIELD_OFFSET(S2C_Message, _impl_.guid_)}},
    // repeated string hashes = 5;
    {::_pbi::TcParser::FastUR1,
     {42, 0, 0,
      PROTOBUF_FIELD_OFFSET(S2C_Message, _impl_.hashes_)}},
    // bytes dll_bytes = 6;
    {::_pbi::TcParser::FastBS1,
     {50, 4, 0,
      PROTOBUF_FIELD_OFFSET(S2C_Message, _impl_.dll_bytes_)}},
    // string dll_hash = 7;
    {::_pbi::TcParser::FastUS1,
     {58, 5, 0,
      PROTOBUF_FIELD_OFFSET(S2C_Message, _impl_.dll_hash_)}},
    // string dll_name = 8;
    {::_pbi::TcParser::FastUS1,
     {66, 6, 0,
      PROTOBUF_FIELD_OFFSET(S2C_Message, _impl_.dll_name_)}},
    // repeated .CheatHaram.Player players_list = 9;
    {::_pbi::TcParser::FastMtR1,
     {74, 1, 0,
      PROTOBUF_FIELD_OFFSET(S2C_Message, _impl_.players_list_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .CheatHaram.ActionType action = 1;
    {PROTOBUF_FIELD_OFFSET(S2C_Message, _impl_.action_), _Internal::kHasBitsOffset + 7, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // bool success = 2;
    {PROTOBUF_FIELD_OFFSET(S2C_Message, _impl_.success_), _Internal::kHasBitsOffset + 8, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // string message = 3;
    {PROTOBUF_FIELD_OFFSET(S2C_Message, _impl_.message_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string guid = 4;
    {PROTOBUF_FIELD_OFFSET(S2C_Message, _impl_.guid_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated string hashes = 5;
    {PROTOBUF_FIELD_OFFSET(S2C_Message, _impl_.hashes_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
    // bytes dll_bytes = 6;
    {PROTOBUF_FIELD_OFFSET(S2C_Message, _impl_.dll_bytes_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // string dll_hash = 7;
    {PROTOBUF_FIELD_OFFSET(S2C_Message, _impl_.dll_hash_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string dll_name = 8;
    {PROTOBUF_FIELD_OFFSET(S2C_Message, _impl_.dll_name_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated .CheatHaram.Player players_list = 9;
    {PROTOBUF_FIELD_OFFSET(S2C_Message, _impl_.players_list_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::CheatHaram::Player>()},
  }},
  {{
    "\26\0\0\7\4\6\0\10\10\0\0\0\0\0\0\0"
    "CheatHaram.S2C_Message"
    "message"
    "guid"
    "hashes"
    "dll_hash"
    "dll_name"
  }},
};
PROTOBUF_NOINLINE void S2C_Message::Clear() {
// @@protoc_insertion_point(message_clear_start:CheatHaram.S2C_Message)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000007fU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _impl_.hashes_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _impl_.players_list_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.message_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _impl_.guid_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _impl_.dll_bytes_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      _impl_.dll_hash_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      _impl_.dll_name_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.action_ = 0;
  _impl_.success_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL S2C_Message::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const S2C_Message& this_ = static_cast<const S2C_Message&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL S2C_Message::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const S2C_Message& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:CheatHaram.S2C_Message)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .CheatHaram.ActionType action = 1;
  if (CheckHasBit(cached_has_bits, 0x00000080U)) {
    if (this_._internal_action() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          1, this_._internal_action(), target);
    }
  }

  // bool success = 2;
  if (CheckHasBit(cached_has_bits, 0x00000100U)) {
    if (this_._internal_success() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          2, this_._internal_success(), target);
    }
  }

  // string message = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_message().empty()) {
      const ::std::string& _s = this_._internal_message();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "CheatHaram.S2C_Message.message");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  // string guid = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (!this_._internal_guid().empty()) {
      const ::std::string& _s = this_._internal_guid();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "CheatHaram.S2C_Message.guid");
      target = stream->WriteStringMaybeAliased(4, _s, target);
    }
  }

  // repeated string hashes = 5;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (int i = 0, n = this_._internal_hashes_size(); i < n; ++i) {
      const auto& s = this_._internal_hashes().Get(i);
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "CheatHaram.S2C_Message.hashes");
      target = stream->WriteString(5, s, target);
    }
  }

  // bytes dll_bytes = 6;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (!this_._internal_dll_bytes().empty()) {
      const ::std::string& _s = this_._internal_dll_bytes();
      target = stream->WriteBytesMaybeAliased(6, _s, target);
    }
  }

  // string dll_hash = 7;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (!this_._internal_dll_hash().empty()) {
      const ::std::string& _s = this_._internal_dll_hash();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "CheatHaram.S2C_Message.dll_hash");
      target = stream->WriteStringMaybeAliased(7, _s, target);
    }
  }

  // string dll_name = 8;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    if (!this_._internal_dll_name().empty()) {
      const ::std::string& _s = this_._internal_dll_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "CheatHaram.S2C_Message.dll_name");
      target = stream->WriteStringMaybeAliased(8, _s, target);
    }
  }

  // repeated .CheatHaram.Player players_list = 9;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_players_list_size());
         i < n; i++) {
      const auto& repfield = this_._internal_players_list().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              9, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CheatHaram.S2C_Message)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t S2C_Message::ByteSizeLong(const MessageLite& base) {
  const S2C_Message& this_ = static_cast<const S2C_Message&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t S2C_Message::ByteSizeLong() const {
  const S2C_Message& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:CheatHaram.S2C_Message)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    // repeated string hashes = 5;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_hashes().size());
      for (int i = 0, n = this_._internal_hashes().size(); i < n; ++i) {
        total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
            this_._internal_hashes().Get(i));
      }
    }
    // repeated .CheatHaram.Player players_list = 9;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      total_size += 1UL * this_._internal_players_list_size();
      for (const auto& msg : this_._internal_players_list()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // string message = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_message().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_message());
      }
    }
    // string guid = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!this_._internal_guid().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_guid());
      }
    }
    // bytes dll_bytes = 6;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (!this_._internal_dll_bytes().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_dll_bytes());
      }
    }
    // string dll_hash = 7;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (!this_._internal_dll_hash().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_dll_hash());
      }
    }
    // string dll_name = 8;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (!this_._internal_dll_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_dll_name());
      }
    }
    // .CheatHaram.ActionType action = 1;
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (this_._internal_action() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_action());
      }
    }
  }
   {
    // bool success = 2;
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      if (this_._internal_success() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void S2C_Message::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<S2C_Message*>(&to_msg);
  auto& from = static_cast<const S2C_Message&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:CheatHaram.S2C_Message)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_hashes()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_hashes());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _this->_internal_mutable_players_list()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_players_list());
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_message().empty()) {
        _this->_internal_set_message(from._internal_message());
      } else {
        if (_this->_impl_.message_.IsDefault()) {
          _this->_internal_set_message("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!from._internal_guid().empty()) {
        _this->_internal_set_guid(from._internal_guid());
      } else {
        if (_this->_impl_.guid_.IsDefault()) {
          _this->_internal_set_guid("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (!from._internal_dll_bytes().empty()) {
        _this->_internal_set_dll_bytes(from._internal_dll_bytes());
      } else {
        if (_this->_impl_.dll_bytes_.IsDefault()) {
          _this->_internal_set_dll_bytes("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (!from._internal_dll_hash().empty()) {
        _this->_internal_set_dll_hash(from._internal_dll_hash());
      } else {
        if (_this->_impl_.dll_hash_.IsDefault()) {
          _this->_internal_set_dll_hash("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (!from._internal_dll_name().empty()) {
        _this->_internal_set_dll_name(from._internal_dll_name());
      } else {
        if (_this->_impl_.dll_name_.IsDefault()) {
          _this->_internal_set_dll_name("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (from._internal_action() != 0) {
        _this->_impl_.action_ = from._impl_.action_;
      }
    }
  }
  if (CheckHasBit(cached_has_bits, 0x00000100U)) {
    if (from._internal_success() != 0) {
      _this->_impl_.success_ = from._impl_.success_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void S2C_Message::CopyFrom(const S2C_Message& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:CheatHaram.S2C_Message)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void S2C_Message::InternalSwap(S2C_Message* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.hashes_.InternalSwap(&other->_impl_.hashes_);
  _impl_.players_list_.InternalSwap(&other->_impl_.players_list_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.guid_, &other->_impl_.guid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.dll_bytes_, &other->_impl_.dll_bytes_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.dll_hash_, &other->_impl_.dll_hash_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.dll_name_, &other->_impl_.dll_name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(S2C_Message, _impl_.success_)
      + sizeof(S2C_Message::_impl_.success_)
      - PROTOBUF_FIELD_OFFSET(S2C_Message, _impl_.action_)>(
          reinterpret_cast<char*>(&_impl_.action_),
          reinterpret_cast<char*>(&other->_impl_.action_));
}

::google::protobuf::Metadata S2C_Message::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace CheatHaram
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_messages_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
