// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto
// Protobuf C++ Version: 6.33.4

#ifndef messages_2eproto_2epb_2eh
#define messages_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_messages_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_messages_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_messages_2eproto;
}  // extern "C"
namespace CheatHaram {
enum ActionType : int;
extern const uint32_t ActionType_internal_data_[];
class C2S_Message;
struct C2S_MessageDefaultTypeInternal;
extern C2S_MessageDefaultTypeInternal _C2S_Message_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull C2S_Message_class_data_;
class Player;
struct PlayerDefaultTypeInternal;
extern PlayerDefaultTypeInternal _Player_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Player_class_data_;
class PlayerData;
struct PlayerDataDefaultTypeInternal;
extern PlayerDataDefaultTypeInternal _PlayerData_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PlayerData_class_data_;
class S2C_Message;
struct S2C_MessageDefaultTypeInternal;
extern S2C_MessageDefaultTypeInternal _S2C_Message_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull S2C_Message_class_data_;
}  // namespace CheatHaram
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::CheatHaram::ActionType_internal_data_>
    internal::EnumTraitsImpl::value<::CheatHaram::ActionType>;
}  // namespace protobuf
}  // namespace google

namespace CheatHaram {
enum ActionType : int {
  UNKNOWN = 0,
  AUTH_REQUEST = 1,
  AUTH_RESULT = 2,
  PK3_WHITELIST_REQ = 3,
  PK3_WHITELIST_RESULT = 4,
  PAYLOAD_REQ = 5,
  PAYLOAD_RESULT = 6,
  SET_GUID = 7,
  CRASH_CLIENT = 8,
  PLAYER_LIST_REQ = 9,
  PLAYER_LIST_RESULT = 10,
  TAKE_FAIRSHOT = 11,
  REQUEST_FAIRSHOT = 12,
  HEARTBEAT = 13,
  UPDATE_PLAYER_STATE = 14,
  GET_GUID_REQ = 15,
  ActionType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  ActionType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t ActionType_internal_data_[];
inline constexpr ActionType ActionType_MIN =
    static_cast<ActionType>(0);
inline constexpr ActionType ActionType_MAX =
    static_cast<ActionType>(15);
inline bool ActionType_IsValid(int value) {
  return 0 <= value && value <= 15;
}
inline constexpr int ActionType_ARRAYSIZE = 15 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL ActionType_descriptor();
template <typename T>
const ::std::string& ActionType_Name(T value) {
  static_assert(::std::is_same<T, ActionType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to ActionType_Name().");
  return ActionType_Name(static_cast<ActionType>(value));
}
template <>
inline const ::std::string& ActionType_Name(ActionType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<ActionType_descriptor, 0, 15>(
      static_cast<int>(value));
}
inline bool ActionType_Parse(
    ::absl::string_view name, ActionType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<ActionType>(ActionType_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class PlayerData final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:CheatHaram.PlayerData) */ {
 public:
  inline PlayerData() : PlayerData(nullptr) {}
  ~PlayerData() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PlayerData* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PlayerData));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PlayerData(::google::protobuf::internal::ConstantInitialized);

  inline PlayerData(const PlayerData& from) : PlayerData(nullptr, from) {}
  inline PlayerData(PlayerData&& from) noexcept
      : PlayerData(nullptr, ::std::move(from)) {}
  inline PlayerData& operator=(const PlayerData& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerData& operator=(PlayerData&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlayerData& default_instance() {
    return *reinterpret_cast<const PlayerData*>(
        &_PlayerData_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(PlayerData& a, PlayerData& b) { a.Swap(&b); }
  inline void Swap(PlayerData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlayerData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlayerData* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PlayerData>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PlayerData& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PlayerData& from) { PlayerData::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PlayerData* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "CheatHaram.PlayerData"; }

  explicit PlayerData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PlayerData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PlayerData& from);
  PlayerData(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PlayerData&& from) noexcept
      : PlayerData(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNameFieldNumber = 2,
    kServerIpFieldNumber = 3,
    kIdFieldNumber = 1,
    kInGameFieldNumber = 4,
  };
  // string name = 2;
  void clear_name() ;
  const ::std::string& name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_name();
  void set_allocated_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_name();

  public:
  // string server_ip = 3;
  void clear_server_ip() ;
  const ::std::string& server_ip() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_server_ip(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_server_ip();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_server_ip();
  void set_allocated_server_ip(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_server_ip() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_server_ip(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_server_ip();

  public:
  // int32 id = 1;
  void clear_id() ;
  ::int32_t id() const;
  void set_id(::int32_t value);

  private:
  ::int32_t _internal_id() const;
  void _internal_set_id(::int32_t value);

  public:
  // bool in_game = 4;
  void clear_in_game() ;
  bool in_game() const;
  void set_in_game(bool value);

  private:
  bool _internal_in_game() const;
  void _internal_set_in_game(bool value);

  public:
  // @@protoc_insertion_point(class_scope:CheatHaram.PlayerData)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 43,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PlayerData& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::google::protobuf::internal::ArenaStringPtr server_ip_;
    ::int32_t id_;
    bool in_game_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_messages_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PlayerData_class_data_;
// -------------------------------------------------------------------

class Player final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:CheatHaram.Player) */ {
 public:
  inline Player() : Player(nullptr) {}
  ~Player() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Player* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Player));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Player(::google::protobuf::internal::ConstantInitialized);

  inline Player(const Player& from) : Player(nullptr, from) {}
  inline Player(Player&& from) noexcept
      : Player(nullptr, ::std::move(from)) {}
  inline Player& operator=(const Player& from) {
    CopyFrom(from);
    return *this;
  }
  inline Player& operator=(Player&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Player& default_instance() {
    return *reinterpret_cast<const Player*>(
        &_Player_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Player& a, Player& b) { a.Swap(&b); }
  inline void Swap(Player* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Player* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Player* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Player>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Player& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Player& from) { Player::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Player* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "CheatHaram.Player"; }

  explicit Player(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Player(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Player& from);
  Player(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Player&& from) noexcept
      : Player(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kGuidFieldNumber = 2,
    kNameFieldNumber = 3,
    kIdFieldNumber = 1,
  };
  // string guid = 2;
  void clear_guid() ;
  const ::std::string& guid() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_guid(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_guid();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_guid();
  void set_allocated_guid(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_guid() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_guid(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_guid();

  public:
  // string name = 3;
  void clear_name() ;
  const ::std::string& name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_name();
  void set_allocated_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_name();

  public:
  // int32 id = 1;
  void clear_id() ;
  ::int32_t id() const;
  void set_id(::int32_t value);

  private:
  ::int32_t _internal_id() const;
  void _internal_set_id(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:CheatHaram.Player)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 34,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Player& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr guid_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::int32_t id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_messages_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Player_class_data_;
// -------------------------------------------------------------------

class S2C_Message final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:CheatHaram.S2C_Message) */ {
 public:
  inline S2C_Message() : S2C_Message(nullptr) {}
  ~S2C_Message() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(S2C_Message* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(S2C_Message));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR S2C_Message(::google::protobuf::internal::ConstantInitialized);

  inline S2C_Message(const S2C_Message& from) : S2C_Message(nullptr, from) {}
  inline S2C_Message(S2C_Message&& from) noexcept
      : S2C_Message(nullptr, ::std::move(from)) {}
  inline S2C_Message& operator=(const S2C_Message& from) {
    CopyFrom(from);
    return *this;
  }
  inline S2C_Message& operator=(S2C_Message&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S2C_Message& default_instance() {
    return *reinterpret_cast<const S2C_Message*>(
        &_S2C_Message_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(S2C_Message& a, S2C_Message& b) { a.Swap(&b); }
  inline void Swap(S2C_Message* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S2C_Message* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S2C_Message* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<S2C_Message>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const S2C_Message& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const S2C_Message& from) { S2C_Message::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(S2C_Message* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "CheatHaram.S2C_Message"; }

  explicit S2C_Message(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  S2C_Message(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const S2C_Message& from);
  S2C_Message(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, S2C_Message&& from) noexcept
      : S2C_Message(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kHashesFieldNumber = 5,
    kPlayersListFieldNumber = 9,
    kMessageFieldNumber = 3,
    kGuidFieldNumber = 4,
    kDllBytesFieldNumber = 6,
    kDllHashFieldNumber = 7,
    kDllNameFieldNumber = 8,
    kActionFieldNumber = 1,
    kSuccessFieldNumber = 2,
  };
  // repeated string hashes = 5;
  int hashes_size() const;
  private:
  int _internal_hashes_size() const;

  public:
  void clear_hashes() ;
  const ::std::string& hashes(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_hashes(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_hashes(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_hashes();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_hashes(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<::std::string>& hashes() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL mutable_hashes();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_hashes() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_hashes();

  public:
  // repeated .CheatHaram.Player players_list = 9;
  int players_list_size() const;
  private:
  int _internal_players_list_size() const;

  public:
  void clear_players_list() ;
  ::CheatHaram::Player* PROTOBUF_NONNULL mutable_players_list(int index);
  ::google::protobuf::RepeatedPtrField<::CheatHaram::Player>* PROTOBUF_NONNULL mutable_players_list();

  private:
  const ::google::protobuf::RepeatedPtrField<::CheatHaram::Player>& _internal_players_list() const;
  ::google::protobuf::RepeatedPtrField<::CheatHaram::Player>* PROTOBUF_NONNULL _internal_mutable_players_list();
  public:
  const ::CheatHaram::Player& players_list(int index) const;
  ::CheatHaram::Player* PROTOBUF_NONNULL add_players_list();
  const ::google::protobuf::RepeatedPtrField<::CheatHaram::Player>& players_list() const;
  // string message = 3;
  void clear_message() ;
  const ::std::string& message() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_message(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_message();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_message();
  void set_allocated_message(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_message() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_message(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_message();

  public:
  // string guid = 4;
  void clear_guid() ;
  const ::std::string& guid() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_guid(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_guid();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_guid();
  void set_allocated_guid(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_guid() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_guid(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_guid();

  public:
  // string dll_bytes = 6;
  void clear_dll_bytes() ;
  const ::std::string& dll_bytes() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_dll_bytes(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_dll_bytes();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_dll_bytes();
  void set_allocated_dll_bytes(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_dll_bytes() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_dll_bytes(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_dll_bytes();

  public:
  // string dll_hash = 7;
  void clear_dll_hash() ;
  const ::std::string& dll_hash() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_dll_hash(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_dll_hash();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_dll_hash();
  void set_allocated_dll_hash(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_dll_hash() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_dll_hash(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_dll_hash();

  public:
  // string dll_name = 8;
  void clear_dll_name() ;
  const ::std::string& dll_name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_dll_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_dll_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_dll_name();
  void set_allocated_dll_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_dll_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_dll_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_dll_name();

  public:
  // .CheatHaram.ActionType action = 1;
  void clear_action() ;
  ::CheatHaram::ActionType action() const;
  void set_action(::CheatHaram::ActionType value);

  private:
  ::CheatHaram::ActionType _internal_action() const;
  void _internal_set_action(::CheatHaram::ActionType value);

  public:
  // bool success = 2;
  void clear_success() ;
  bool success() const;
  void set_success(bool value);

  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);

  public:
  // @@protoc_insertion_point(class_scope:CheatHaram.S2C_Message)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<4, 9,
                                   1, 81,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const S2C_Message& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField<::std::string> hashes_;
    ::google::protobuf::RepeatedPtrField< ::CheatHaram::Player > players_list_;
    ::google::protobuf::internal::ArenaStringPtr message_;
    ::google::protobuf::internal::ArenaStringPtr guid_;
    ::google::protobuf::internal::ArenaStringPtr dll_bytes_;
    ::google::protobuf::internal::ArenaStringPtr dll_hash_;
    ::google::protobuf::internal::ArenaStringPtr dll_name_;
    int action_;
    bool success_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_messages_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull S2C_Message_class_data_;
// -------------------------------------------------------------------

class C2S_Message final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:CheatHaram.C2S_Message) */ {
 public:
  inline C2S_Message() : C2S_Message(nullptr) {}
  ~C2S_Message() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(C2S_Message* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(C2S_Message));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR C2S_Message(::google::protobuf::internal::ConstantInitialized);

  inline C2S_Message(const C2S_Message& from) : C2S_Message(nullptr, from) {}
  inline C2S_Message(C2S_Message&& from) noexcept
      : C2S_Message(nullptr, ::std::move(from)) {}
  inline C2S_Message& operator=(const C2S_Message& from) {
    CopyFrom(from);
    return *this;
  }
  inline C2S_Message& operator=(C2S_Message&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C2S_Message& default_instance() {
    return *reinterpret_cast<const C2S_Message*>(
        &_C2S_Message_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(C2S_Message& a, C2S_Message& b) { a.Swap(&b); }
  inline void Swap(C2S_Message* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C2S_Message* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C2S_Message* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<C2S_Message>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const C2S_Message& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const C2S_Message& from) { C2S_Message::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(C2S_Message* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "CheatHaram.C2S_Message"; }

  explicit C2S_Message(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  C2S_Message(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const C2S_Message& from);
  C2S_Message(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, C2S_Message&& from) noexcept
      : C2S_Message(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSignatureFieldNumber = 3,
    kImageDataFieldNumber = 5,
    kTargetFieldNumber = 6,
    kPlayerDataFieldNumber = 4,
    kTimestampFieldNumber = 2,
    kActionFieldNumber = 1,
  };
  // string signature = 3;
  void clear_signature() ;
  const ::std::string& signature() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_signature(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_signature();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_signature();
  void set_allocated_signature(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_signature() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_signature(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_signature();

  public:
  // bytes image_data = 5;
  void clear_image_data() ;
  const ::std::string& image_data() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_image_data(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_image_data();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_image_data();
  void set_allocated_image_data(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_image_data() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_image_data(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_image_data();

  public:
  // string target = 6;
  void clear_target() ;
  const ::std::string& target() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_target(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_target();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_target();
  void set_allocated_target(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_target() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_target(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_target();

  public:
  // .CheatHaram.PlayerData player_data = 4;
  bool has_player_data() const;
  void clear_player_data() ;
  const ::CheatHaram::PlayerData& player_data() const;
  [[nodiscard]] ::CheatHaram::PlayerData* PROTOBUF_NULLABLE release_player_data();
  ::CheatHaram::PlayerData* PROTOBUF_NONNULL mutable_player_data();
  void set_allocated_player_data(::CheatHaram::PlayerData* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_player_data(::CheatHaram::PlayerData* PROTOBUF_NULLABLE value);
  ::CheatHaram::PlayerData* PROTOBUF_NULLABLE unsafe_arena_release_player_data();

  private:
  const ::CheatHaram::PlayerData& _internal_player_data() const;
  ::CheatHaram::PlayerData* PROTOBUF_NONNULL _internal_mutable_player_data();

  public:
  // uint64 timestamp = 2;
  void clear_timestamp() ;
  ::uint64_t timestamp() const;
  void set_timestamp(::uint64_t value);

  private:
  ::uint64_t _internal_timestamp() const;
  void _internal_set_timestamp(::uint64_t value);

  public:
  // .CheatHaram.ActionType action = 1;
  void clear_action() ;
  ::CheatHaram::ActionType action() const;
  void set_action(::CheatHaram::ActionType value);

  private:
  ::CheatHaram::ActionType _internal_action() const;
  void _internal_set_action(::CheatHaram::ActionType value);

  public:
  // @@protoc_insertion_point(class_scope:CheatHaram.C2S_Message)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 6,
                                   1, 46,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const C2S_Message& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr signature_;
    ::google::protobuf::internal::ArenaStringPtr image_data_;
    ::google::protobuf::internal::ArenaStringPtr target_;
    ::CheatHaram::PlayerData* PROTOBUF_NULLABLE player_data_;
    ::uint64_t timestamp_;
    int action_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_messages_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull C2S_Message_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Player

// int32 id = 1;
inline void Player::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int32_t Player::id() const {
  // @@protoc_insertion_point(field_get:CheatHaram.Player.id)
  return _internal_id();
}
inline void Player::set_id(::int32_t value) {
  _internal_set_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:CheatHaram.Player.id)
}
inline ::int32_t Player::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void Player::_internal_set_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// string guid = 2;
inline void Player::clear_guid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.guid_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& Player::guid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CheatHaram.Player.guid)
  return _internal_guid();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Player::set_guid(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.guid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:CheatHaram.Player.guid)
}
inline ::std::string* PROTOBUF_NONNULL Player::mutable_guid()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_guid();
  // @@protoc_insertion_point(field_mutable:CheatHaram.Player.guid)
  return _s;
}
inline const ::std::string& Player::_internal_guid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.guid_.Get();
}
inline void Player::_internal_set_guid(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.guid_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Player::_internal_mutable_guid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.guid_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Player::release_guid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:CheatHaram.Player.guid)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.guid_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.guid_.Set("", GetArena());
  }
  return released;
}
inline void Player::set_allocated_guid(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.guid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.guid_.IsDefault()) {
    _impl_.guid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:CheatHaram.Player.guid)
}

// string name = 3;
inline void Player::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& Player::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CheatHaram.Player.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Player::set_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:CheatHaram.Player.name)
}
inline ::std::string* PROTOBUF_NONNULL Player::mutable_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:CheatHaram.Player.name)
  return _s;
}
inline const ::std::string& Player::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void Player::_internal_set_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Player::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Player::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:CheatHaram.Player.name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.name_.Set("", GetArena());
  }
  return released;
}
inline void Player::set_allocated_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:CheatHaram.Player.name)
}

// -------------------------------------------------------------------

// PlayerData

// int32 id = 1;
inline void PlayerData::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int32_t PlayerData::id() const {
  // @@protoc_insertion_point(field_get:CheatHaram.PlayerData.id)
  return _internal_id();
}
inline void PlayerData::set_id(::int32_t value) {
  _internal_set_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:CheatHaram.PlayerData.id)
}
inline ::int32_t PlayerData::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void PlayerData::_internal_set_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// string name = 2;
inline void PlayerData::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& PlayerData::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CheatHaram.PlayerData.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PlayerData::set_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:CheatHaram.PlayerData.name)
}
inline ::std::string* PROTOBUF_NONNULL PlayerData::mutable_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:CheatHaram.PlayerData.name)
  return _s;
}
inline const ::std::string& PlayerData::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void PlayerData::_internal_set_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PlayerData::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PlayerData::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:CheatHaram.PlayerData.name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.name_.Set("", GetArena());
  }
  return released;
}
inline void PlayerData::set_allocated_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:CheatHaram.PlayerData.name)
}

// string server_ip = 3;
inline void PlayerData::clear_server_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.server_ip_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& PlayerData::server_ip() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CheatHaram.PlayerData.server_ip)
  return _internal_server_ip();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PlayerData::set_server_ip(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.server_ip_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:CheatHaram.PlayerData.server_ip)
}
inline ::std::string* PROTOBUF_NONNULL PlayerData::mutable_server_ip()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_server_ip();
  // @@protoc_insertion_point(field_mutable:CheatHaram.PlayerData.server_ip)
  return _s;
}
inline const ::std::string& PlayerData::_internal_server_ip() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.server_ip_.Get();
}
inline void PlayerData::_internal_set_server_ip(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.server_ip_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PlayerData::_internal_mutable_server_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.server_ip_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PlayerData::release_server_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:CheatHaram.PlayerData.server_ip)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.server_ip_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.server_ip_.Set("", GetArena());
  }
  return released;
}
inline void PlayerData::set_allocated_server_ip(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.server_ip_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.server_ip_.IsDefault()) {
    _impl_.server_ip_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:CheatHaram.PlayerData.server_ip)
}

// bool in_game = 4;
inline void PlayerData::clear_in_game() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.in_game_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline bool PlayerData::in_game() const {
  // @@protoc_insertion_point(field_get:CheatHaram.PlayerData.in_game)
  return _internal_in_game();
}
inline void PlayerData::set_in_game(bool value) {
  _internal_set_in_game(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:CheatHaram.PlayerData.in_game)
}
inline bool PlayerData::_internal_in_game() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.in_game_;
}
inline void PlayerData::_internal_set_in_game(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.in_game_ = value;
}

// -------------------------------------------------------------------

// C2S_Message

// .CheatHaram.ActionType action = 1;
inline void C2S_Message::clear_action() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.action_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::CheatHaram::ActionType C2S_Message::action() const {
  // @@protoc_insertion_point(field_get:CheatHaram.C2S_Message.action)
  return _internal_action();
}
inline void C2S_Message::set_action(::CheatHaram::ActionType value) {
  _internal_set_action(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:CheatHaram.C2S_Message.action)
}
inline ::CheatHaram::ActionType C2S_Message::_internal_action() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::CheatHaram::ActionType>(_impl_.action_);
}
inline void C2S_Message::_internal_set_action(::CheatHaram::ActionType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.action_ = value;
}

// uint64 timestamp = 2;
inline void C2S_Message::clear_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::uint64_t C2S_Message::timestamp() const {
  // @@protoc_insertion_point(field_get:CheatHaram.C2S_Message.timestamp)
  return _internal_timestamp();
}
inline void C2S_Message::set_timestamp(::uint64_t value) {
  _internal_set_timestamp(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:CheatHaram.C2S_Message.timestamp)
}
inline ::uint64_t C2S_Message::_internal_timestamp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timestamp_;
}
inline void C2S_Message::_internal_set_timestamp(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ = value;
}

// string signature = 3;
inline void C2S_Message::clear_signature() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.signature_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& C2S_Message::signature() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CheatHaram.C2S_Message.signature)
  return _internal_signature();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void C2S_Message::set_signature(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.signature_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:CheatHaram.C2S_Message.signature)
}
inline ::std::string* PROTOBUF_NONNULL C2S_Message::mutable_signature()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_signature();
  // @@protoc_insertion_point(field_mutable:CheatHaram.C2S_Message.signature)
  return _s;
}
inline const ::std::string& C2S_Message::_internal_signature() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.signature_.Get();
}
inline void C2S_Message::_internal_set_signature(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.signature_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL C2S_Message::_internal_mutable_signature() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.signature_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE C2S_Message::release_signature() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:CheatHaram.C2S_Message.signature)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.signature_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.signature_.Set("", GetArena());
  }
  return released;
}
inline void C2S_Message::set_allocated_signature(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.signature_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.signature_.IsDefault()) {
    _impl_.signature_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:CheatHaram.C2S_Message.signature)
}

// .CheatHaram.PlayerData player_data = 4;
inline bool C2S_Message::has_player_data() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  PROTOBUF_ASSUME(!value || _impl_.player_data_ != nullptr);
  return value;
}
inline void C2S_Message::clear_player_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.player_data_ != nullptr) _impl_.player_data_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline const ::CheatHaram::PlayerData& C2S_Message::_internal_player_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::CheatHaram::PlayerData* p = _impl_.player_data_;
  return p != nullptr ? *p : reinterpret_cast<const ::CheatHaram::PlayerData&>(::CheatHaram::_PlayerData_default_instance_);
}
inline const ::CheatHaram::PlayerData& C2S_Message::player_data() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CheatHaram.C2S_Message.player_data)
  return _internal_player_data();
}
inline void C2S_Message::unsafe_arena_set_allocated_player_data(
    ::CheatHaram::PlayerData* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.player_data_);
  }
  _impl_.player_data_ = reinterpret_cast<::CheatHaram::PlayerData*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:CheatHaram.C2S_Message.player_data)
}
inline ::CheatHaram::PlayerData* PROTOBUF_NULLABLE C2S_Message::release_player_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::CheatHaram::PlayerData* released = _impl_.player_data_;
  _impl_.player_data_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::CheatHaram::PlayerData* PROTOBUF_NULLABLE C2S_Message::unsafe_arena_release_player_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:CheatHaram.C2S_Message.player_data)

  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::CheatHaram::PlayerData* temp = _impl_.player_data_;
  _impl_.player_data_ = nullptr;
  return temp;
}
inline ::CheatHaram::PlayerData* PROTOBUF_NONNULL C2S_Message::_internal_mutable_player_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.player_data_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::CheatHaram::PlayerData>(GetArena());
    _impl_.player_data_ = reinterpret_cast<::CheatHaram::PlayerData*>(p);
  }
  return _impl_.player_data_;
}
inline ::CheatHaram::PlayerData* PROTOBUF_NONNULL C2S_Message::mutable_player_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::CheatHaram::PlayerData* _msg = _internal_mutable_player_data();
  // @@protoc_insertion_point(field_mutable:CheatHaram.C2S_Message.player_data)
  return _msg;
}
inline void C2S_Message::set_allocated_player_data(::CheatHaram::PlayerData* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.player_data_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }

  _impl_.player_data_ = reinterpret_cast<::CheatHaram::PlayerData*>(value);
  // @@protoc_insertion_point(field_set_allocated:CheatHaram.C2S_Message.player_data)
}

// bytes image_data = 5;
inline void C2S_Message::clear_image_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.image_data_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& C2S_Message::image_data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CheatHaram.C2S_Message.image_data)
  return _internal_image_data();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void C2S_Message::set_image_data(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.image_data_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:CheatHaram.C2S_Message.image_data)
}
inline ::std::string* PROTOBUF_NONNULL C2S_Message::mutable_image_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_image_data();
  // @@protoc_insertion_point(field_mutable:CheatHaram.C2S_Message.image_data)
  return _s;
}
inline const ::std::string& C2S_Message::_internal_image_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.image_data_.Get();
}
inline void C2S_Message::_internal_set_image_data(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.image_data_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL C2S_Message::_internal_mutable_image_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.image_data_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE C2S_Message::release_image_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:CheatHaram.C2S_Message.image_data)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.image_data_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.image_data_.Set("", GetArena());
  }
  return released;
}
inline void C2S_Message::set_allocated_image_data(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.image_data_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.image_data_.IsDefault()) {
    _impl_.image_data_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:CheatHaram.C2S_Message.image_data)
}

// string target = 6;
inline void C2S_Message::clear_target() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.target_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& C2S_Message::target() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CheatHaram.C2S_Message.target)
  return _internal_target();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void C2S_Message::set_target(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.target_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:CheatHaram.C2S_Message.target)
}
inline ::std::string* PROTOBUF_NONNULL C2S_Message::mutable_target()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_target();
  // @@protoc_insertion_point(field_mutable:CheatHaram.C2S_Message.target)
  return _s;
}
inline const ::std::string& C2S_Message::_internal_target() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.target_.Get();
}
inline void C2S_Message::_internal_set_target(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.target_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL C2S_Message::_internal_mutable_target() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.target_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE C2S_Message::release_target() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:CheatHaram.C2S_Message.target)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.target_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.target_.Set("", GetArena());
  }
  return released;
}
inline void C2S_Message::set_allocated_target(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.target_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.target_.IsDefault()) {
    _impl_.target_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:CheatHaram.C2S_Message.target)
}

// -------------------------------------------------------------------

// S2C_Message

// .CheatHaram.ActionType action = 1;
inline void S2C_Message::clear_action() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.action_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000080U);
}
inline ::CheatHaram::ActionType S2C_Message::action() const {
  // @@protoc_insertion_point(field_get:CheatHaram.S2C_Message.action)
  return _internal_action();
}
inline void S2C_Message::set_action(::CheatHaram::ActionType value) {
  _internal_set_action(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_set:CheatHaram.S2C_Message.action)
}
inline ::CheatHaram::ActionType S2C_Message::_internal_action() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::CheatHaram::ActionType>(_impl_.action_);
}
inline void S2C_Message::_internal_set_action(::CheatHaram::ActionType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.action_ = value;
}

// bool success = 2;
inline void S2C_Message::clear_success() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000100U);
}
inline bool S2C_Message::success() const {
  // @@protoc_insertion_point(field_get:CheatHaram.S2C_Message.success)
  return _internal_success();
}
inline void S2C_Message::set_success(bool value) {
  _internal_set_success(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000100U);
  // @@protoc_insertion_point(field_set:CheatHaram.S2C_Message.success)
}
inline bool S2C_Message::_internal_success() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.success_;
}
inline void S2C_Message::_internal_set_success(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = value;
}

// string message = 3;
inline void S2C_Message::clear_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& S2C_Message::message() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CheatHaram.S2C_Message.message)
  return _internal_message();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void S2C_Message::set_message(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.message_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:CheatHaram.S2C_Message.message)
}
inline ::std::string* PROTOBUF_NONNULL S2C_Message::mutable_message()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:CheatHaram.S2C_Message.message)
  return _s;
}
inline const ::std::string& S2C_Message::_internal_message() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.message_.Get();
}
inline void S2C_Message::_internal_set_message(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL S2C_Message::_internal_mutable_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.message_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE S2C_Message::release_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:CheatHaram.S2C_Message.message)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.message_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.message_.Set("", GetArena());
  }
  return released;
}
inline void S2C_Message::set_allocated_message(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.message_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:CheatHaram.S2C_Message.message)
}

// string guid = 4;
inline void S2C_Message::clear_guid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.guid_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline const ::std::string& S2C_Message::guid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CheatHaram.S2C_Message.guid)
  return _internal_guid();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void S2C_Message::set_guid(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.guid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:CheatHaram.S2C_Message.guid)
}
inline ::std::string* PROTOBUF_NONNULL S2C_Message::mutable_guid()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::std::string* _s = _internal_mutable_guid();
  // @@protoc_insertion_point(field_mutable:CheatHaram.S2C_Message.guid)
  return _s;
}
inline const ::std::string& S2C_Message::_internal_guid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.guid_.Get();
}
inline void S2C_Message::_internal_set_guid(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.guid_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL S2C_Message::_internal_mutable_guid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.guid_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE S2C_Message::release_guid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:CheatHaram.S2C_Message.guid)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000008U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  auto* released = _impl_.guid_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.guid_.Set("", GetArena());
  }
  return released;
}
inline void S2C_Message::set_allocated_guid(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  _impl_.guid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.guid_.IsDefault()) {
    _impl_.guid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:CheatHaram.S2C_Message.guid)
}

// repeated string hashes = 5;
inline int S2C_Message::_internal_hashes_size() const {
  return _internal_hashes().size();
}
inline int S2C_Message::hashes_size() const {
  return _internal_hashes_size();
}
inline void S2C_Message::clear_hashes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hashes_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::std::string* PROTOBUF_NONNULL S2C_Message::add_hashes()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s =
      _internal_mutable_hashes()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add_mutable:CheatHaram.S2C_Message.hashes)
  return _s;
}
inline const ::std::string& S2C_Message::hashes(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CheatHaram.S2C_Message.hashes)
  return _internal_hashes().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL S2C_Message::mutable_hashes(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:CheatHaram.S2C_Message.hashes)
  return _internal_mutable_hashes()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void S2C_Message::set_hashes(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_hashes()->Mutable(index), ::std::forward<Arg_>(value),
                        args... );
  // @@protoc_insertion_point(field_set:CheatHaram.S2C_Message.hashes)
}
template <typename Arg_, typename... Args_>
inline void S2C_Message::add_hashes(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(
      ::google::protobuf::MessageLite::internal_visibility(), GetArena(),
      *_internal_mutable_hashes(), ::std::forward<Arg_>(value),
      args... );
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:CheatHaram.S2C_Message.hashes)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& S2C_Message::hashes()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:CheatHaram.S2C_Message.hashes)
  return _internal_hashes();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
S2C_Message::mutable_hashes() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:CheatHaram.S2C_Message.hashes)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_hashes();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
S2C_Message::_internal_hashes() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.hashes_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
S2C_Message::_internal_mutable_hashes() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.hashes_;
}

// string dll_bytes = 6;
inline void S2C_Message::clear_dll_bytes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dll_bytes_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline const ::std::string& S2C_Message::dll_bytes() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CheatHaram.S2C_Message.dll_bytes)
  return _internal_dll_bytes();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void S2C_Message::set_dll_bytes(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  _impl_.dll_bytes_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:CheatHaram.S2C_Message.dll_bytes)
}
inline ::std::string* PROTOBUF_NONNULL S2C_Message::mutable_dll_bytes()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::std::string* _s = _internal_mutable_dll_bytes();
  // @@protoc_insertion_point(field_mutable:CheatHaram.S2C_Message.dll_bytes)
  return _s;
}
inline const ::std::string& S2C_Message::_internal_dll_bytes() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.dll_bytes_.Get();
}
inline void S2C_Message::_internal_set_dll_bytes(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dll_bytes_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL S2C_Message::_internal_mutable_dll_bytes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.dll_bytes_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE S2C_Message::release_dll_bytes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:CheatHaram.S2C_Message.dll_bytes)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000010U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  auto* released = _impl_.dll_bytes_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.dll_bytes_.Set("", GetArena());
  }
  return released;
}
inline void S2C_Message::set_allocated_dll_bytes(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  }
  _impl_.dll_bytes_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.dll_bytes_.IsDefault()) {
    _impl_.dll_bytes_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:CheatHaram.S2C_Message.dll_bytes)
}

// string dll_hash = 7;
inline void S2C_Message::clear_dll_hash() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dll_hash_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline const ::std::string& S2C_Message::dll_hash() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CheatHaram.S2C_Message.dll_hash)
  return _internal_dll_hash();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void S2C_Message::set_dll_hash(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  _impl_.dll_hash_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:CheatHaram.S2C_Message.dll_hash)
}
inline ::std::string* PROTOBUF_NONNULL S2C_Message::mutable_dll_hash()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  ::std::string* _s = _internal_mutable_dll_hash();
  // @@protoc_insertion_point(field_mutable:CheatHaram.S2C_Message.dll_hash)
  return _s;
}
inline const ::std::string& S2C_Message::_internal_dll_hash() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.dll_hash_.Get();
}
inline void S2C_Message::_internal_set_dll_hash(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dll_hash_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL S2C_Message::_internal_mutable_dll_hash() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.dll_hash_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE S2C_Message::release_dll_hash() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:CheatHaram.S2C_Message.dll_hash)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000020U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000020U);
  auto* released = _impl_.dll_hash_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.dll_hash_.Set("", GetArena());
  }
  return released;
}
inline void S2C_Message::set_allocated_dll_hash(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000020U);
  }
  _impl_.dll_hash_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.dll_hash_.IsDefault()) {
    _impl_.dll_hash_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:CheatHaram.S2C_Message.dll_hash)
}

// string dll_name = 8;
inline void S2C_Message::clear_dll_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dll_name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline const ::std::string& S2C_Message::dll_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CheatHaram.S2C_Message.dll_name)
  return _internal_dll_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void S2C_Message::set_dll_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  _impl_.dll_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:CheatHaram.S2C_Message.dll_name)
}
inline ::std::string* PROTOBUF_NONNULL S2C_Message::mutable_dll_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  ::std::string* _s = _internal_mutable_dll_name();
  // @@protoc_insertion_point(field_mutable:CheatHaram.S2C_Message.dll_name)
  return _s;
}
inline const ::std::string& S2C_Message::_internal_dll_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.dll_name_.Get();
}
inline void S2C_Message::_internal_set_dll_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dll_name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL S2C_Message::_internal_mutable_dll_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.dll_name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE S2C_Message::release_dll_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:CheatHaram.S2C_Message.dll_name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000040U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000040U);
  auto* released = _impl_.dll_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.dll_name_.Set("", GetArena());
  }
  return released;
}
inline void S2C_Message::set_allocated_dll_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000040U);
  }
  _impl_.dll_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.dll_name_.IsDefault()) {
    _impl_.dll_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:CheatHaram.S2C_Message.dll_name)
}

// repeated .CheatHaram.Player players_list = 9;
inline int S2C_Message::_internal_players_list_size() const {
  return _internal_players_list().size();
}
inline int S2C_Message::players_list_size() const {
  return _internal_players_list_size();
}
inline void S2C_Message::clear_players_list() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.players_list_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::CheatHaram::Player* PROTOBUF_NONNULL S2C_Message::mutable_players_list(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:CheatHaram.S2C_Message.players_list)
  return _internal_mutable_players_list()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::CheatHaram::Player>* PROTOBUF_NONNULL S2C_Message::mutable_players_list()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_mutable_list:CheatHaram.S2C_Message.players_list)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_players_list();
}
inline const ::CheatHaram::Player& S2C_Message::players_list(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CheatHaram.S2C_Message.players_list)
  return _internal_players_list().Get(index);
}
inline ::CheatHaram::Player* PROTOBUF_NONNULL S2C_Message::add_players_list()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::CheatHaram::Player* _add =
      _internal_mutable_players_list()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_add:CheatHaram.S2C_Message.players_list)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::CheatHaram::Player>& S2C_Message::players_list() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:CheatHaram.S2C_Message.players_list)
  return _internal_players_list();
}
inline const ::google::protobuf::RepeatedPtrField<::CheatHaram::Player>&
S2C_Message::_internal_players_list() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.players_list_;
}
inline ::google::protobuf::RepeatedPtrField<::CheatHaram::Player>* PROTOBUF_NONNULL
S2C_Message::_internal_mutable_players_list() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.players_list_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace CheatHaram


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::CheatHaram::ActionType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::CheatHaram::ActionType>() {
  return ::CheatHaram::ActionType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // messages_2eproto_2epb_2eh
